## Multi Variable Regression

### Multi-Variable Linear Regression
* 입력 변수가 1개가 아닌 여러개인 경우 다변수 선형회귀
    * bias 도 입력 변수가 1인 것으로 생각할 수 있다
    * $y = W_0X_0 + W_1X_1 + W_2X_2$
        * $W_0$ : 상수, bias
        * $X_0$ : 1
        * $W_n$ : n번째 계수
        * $X_n$ : n번째 입력 변수
![image.png](https://i.imgur.com/ttVB6jg.png)

### 행렬곱
* 각각의 입력 변수에 대해서 미분을 하기 불편하므로 행렬 연산을 한다.
* 행렬곱 연산은 각각의 계수를 개별적으로 찾는 것을 쉽게 해준다.
* 이 때 전치행렬(Transpose)가 쓸모 있다.
![image.png](https://i.imgur.com/netr7gv.png)

### 행렬곱을 이용한 연산
* $H(X) = WX + b$
* $\begin{bmatrix} w1 & w2 & w3 \end{bmatrix} \times \begin{bmatrix} x1 \\ x2 \\x3\end{bmatrix} = 
\begin{bmatrix} w1 \times x1 + w2 \times x2 + w3 \times x3 \end{bmatrix}$

### bias 제거 단순화
* $H(X) = WX$
*  $\begin{bmatrix} b & w1 & w2 & w3 \end{bmatrix} \times \begin{bmatrix} 1\\ x1 \\ x2 \\x3\end{bmatrix} = 
\begin{bmatrix}b \times 1 +  w1 \times x1 + w2 \times x2 + w3 \times x3 \end{bmatrix}$

### 전치 행렬
* Transpose
![image.png](https://i.imgur.com/0MClWDZ.png)

### 전치행렬을 이용한 연산
* $W = \begin{bmatrix} b\\w1\\w2\\w3\end{bmatrix}, x = \begin{bmatrix} 1 \\x1\\x2\\x3\end{bmatrix}$ 일때
* $H(X) = W^TX$
* $ =  \begin{bmatrix}b & w1 & w2 & w3\end{bmatrix} 
 \times \begin{bmatrix} 1 \\ x1 \\ x2 \\ x3 \end{bmatrix} = 
\begin{bmatrix}b \times1 + w1 \times x1 + w2 \times x2 + w3 \times x3 \end{bmatrix}
$


### 2과목 점수 계산 예제
* 2과목의 시험 점수로 학점을 계산하는 예제를 만들어 보자.
    * 3개의 변수를 사용한다.
        * $x_0$ = 1, bias, 50점 기본점수
        * $x_1$ = 0~50, 가중치 0.7
        * $x_2$ = 0~50, 가중치 0.3
        * $y = 50x_0 + 0.7x_1 + 0.3x_2$

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

In [2]:
m = 50
TRUE_W1, TRUE_W2, TRUE_b = 0.7, 0.3, 50

X1 = np.random.randint(0, 50, (m,1)).astype(np.float32)
X2 = np.random.randint(0, 50, (m,1)).astype(np.float32)

Y = TRUE_W1 * X1 + TRUE_W2 * X2 + TRUE_b

print(np.hstack((X1,X2, Y))[:5])

[[ 1.  10.  53.7]
 [ 3.  40.  64.1]
 [45.  29.  90.2]
 [14.  27.  67.9]
 [ 3.  47.  66.2]]


### 개별 변수로 구현
* 개별 변수 선언

```
x1 = x[:,0]
x2 = x[:,1]

W1 = tf.Variable(tf.random.normal([1]))
W2 = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))
```

* ` hypothesis = W1 * x1 + W2 * x2 + b`

In [3]:
W1 = tf.Variable(tf.random.normal((1,)))
W2 = tf.Variable(tf.random.normal((1,)))
b = tf.Variable(tf.random.normal((1,)))
print(W1, W2, b)

learning_rate = 0.0005
epochs = 40001
for epoch in range(epochs):
    with tf.GradientTape() as tape:
        h = W1 * X1 + W2 * X2 + b
        cost = tf.reduce_mean(tf.square(h-Y))
    gW1, gW2, gb = tape.gradient(cost, [W1, W2, b])
    
    W1.assign_sub(learning_rate * gW1)
    W2.assign_sub(learning_rate * gW2)
    b.assign_sub(learning_rate * gb)
    
    if epoch % 2000 == 0:
        print(f"epoch:{epoch}, cost:{cost.numpy()}")
print(f"Final W1:{W1.numpy()}, W2:{W2.numpy()}, b:{b.numpy()}")

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.6335303], dtype=float32)> <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-2.1107354], dtype=float32)> <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-1.0693436], dtype=float32)>
epoch:0, cost:11842.27734375
epoch:2000, cost:222.41094970703125
epoch:4000, cost:114.44172668457031
epoch:6000, cost:58.88628387451172
epoch:8000, cost:30.30010223388672
epoch:10000, cost:15.590920448303223
epoch:12000, cost:8.022322654724121
epoch:14000, cost:4.1278910636901855
epoch:16000, cost:2.124007225036621
epoch:18000, cost:1.0929113626480103
epoch:20000, cost:0.5623711347579956
epoch:22000, cost:0.28935620188713074
epoch:24000, cost:0.14890198409557343
epoch:26000, cost:0.07661141455173492
epoch:28000, cost:0.03943201154470444
epoch:30000, cost:0.020295336842536926
epoch:32000, cost:0.010451162233948708
epoch:34000, cost:0.005382392555475235
epoch:36000, cost:0.0027645432855933905
epoch:38000, cost:0

### Matrix로 구현
* `W = tf.Variable(tf.random.normal([2,1]))`
* `hypothesis = tf.matmul(x, W) + b`

In [7]:
a = np.arange(12).reshape(4,3)
b = tf.constant([[2,3],
                 [2,3],
                 [2,3]])
print(a)
print(b)
print(tf.matmul(a, b))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
tf.Tensor(
[[2 3]
 [2 3]
 [2 3]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 6  9]
 [24 36]
 [42 63]
 [60 90]], shape=(4, 2), dtype=int32)


In [3]:
X = np.hstack((X1, X2))
print(X[:5])

W = tf.Variable(tf.random.normal([2,1]))
b = tf.Variable(tf.random.normal((1, )))
lr = 0.0005
epochs = 40001

for epoch in range(epochs):
    with tf.GradientTape() as tape:
        h = tf.matmul(X, W) + b
        cost = tf.reduce_mean(tf.square(h-Y))
    dW, db = tape.gradient(cost, [W, b])
    W.assign_sub(lr * dW)
    b.assign_sub(lr * db)
    
    if epoch % 2000 == 0:
        print(f"epoch:{epoch}, cost:{cost.numpy()}")
print(f"Final W:{W.numpy()}, b:{b.numpy()}")

[[ 1. 10.]
 [ 3. 40.]
 [45. 29.]
 [14. 27.]
 [ 3. 47.]]
epoch:0, cost:23724.546875
epoch:2000, cost:189.50196838378906
epoch:4000, cost:116.39498138427734
epoch:6000, cost:71.49159240722656
epoch:8000, cost:43.911285400390625
epoch:10000, cost:26.971010208129883
epoch:12000, cost:16.566003799438477
epoch:14000, cost:10.175074577331543
epoch:16000, cost:6.249683380126953
epoch:18000, cost:3.838665246963501
epoch:20000, cost:2.357754707336426
epoch:22000, cost:1.4481985569000244
epoch:24000, cost:0.8895040154457092
epoch:26000, cost:0.546344518661499
epoch:28000, cost:0.33559051156044006
epoch:30000, cost:0.2061057686805725
epoch:32000, cost:0.12659282982349396
epoch:34000, cost:0.07774952799081802
epoch:36000, cost:0.04777974262833595
epoch:38000, cost:0.02934126928448677
epoch:40000, cost:0.018029391765594482
Final W:[[0.7051337 ]
 [0.30807984]], b:[49.615498]
